### PR TITLE
Update README.md 

### PR DESCRIPTION
**Pull request by Lapz**
Stylish can't be compiled if sdl2 is not present on the computer.

### CODE REVIEW

**Comment by Thinkofname** [comment]
Its only needed for the example not stylish on a whole. Would you be able to update it to specify that?

**Comment by Lapz** [comment]
I updated the commit

**Comment by Thinkofname** [comment]
Thanks!

**Comment by est31** [comment]
@Thinkofname If I ported the example over to use glutin and work without sdl2 as dependency, would you merge such a pr?

**Comment by Thinkofname** [comment]
@est31 Sure! the only reason I don't use glutin is because I haven't really used it before

**Pull request merged**
