### PR TITLE
cargo upgrade --all + fixed build errors.

### PR DESCRIPTION
**Pull request by anderejd**
Hi,

This seems to be a really cool project :) Is there some kind of a road map? I've been on a GUI framework hunt for Rust for quite some time now and this is by far the most promising I've found yet, primarily due to webrender being so active, reusing that code seems brilliant. The high frame rate and low CPU usage of the demo looks promising too.

I used `cargo upgrade --all` and in addition to upgrading all dependencies it also reordered some parts of the toml files.

I was going to take a stab at a resizing bug on macOS as an introduction to the code but wanted to upgrade all dependencies first to avoid hunting something that was solved upstream. That bug is still crawling though. 🐛 

There are comments added at two of the changes that would be good to review.

### CODE REVIEW

**Comment by Thinkofname** [comment]
Thanks for the PR. I've tested this locally and it seems like filters are being applied backwards (i'm guessing due to a upstream change in webrender) so i'm going to hold off a bit until thats worked out (either this end or webrender's).

As for a roadmap there really isn't one. This already meets the requirements I had to use it in my game that i'm working on:
uiexample
so at this point its just me keeping it up to date with webrender.

**Comment by anderejd** [comment]
Ooh, nice, that screenshot looks rather Prison Architect-ish. You should consider putting that in the readme in addition to the demo screenshot.

> it seems like filters are being applied backwards

On macOS the demo looks identical for master and this PR but there's something funny going on with the grey grid box borders:

screen shot 2017-11-18 at 09 53 04

I will probably try it out on windows and linux later today and post some more screenshots.

**Comment by Thinkofname** [comment]
The demo doesn't use multiple filters so doesn't trigger the issue, heres an example:
`filters = filters("brightness", 0.7, "sepia", 2.0, "saturate", 3.0, "hue_rotate", hue),`
Gives top on `master` and bottom after this webrender bump:
filterbug
Reversing the order of the filters fixes the issue. If this was intended by webrender we should reverse the passed filter arguments before passing to webrender

**Comment by anderejd** [comment]
> Reversing the order of the filters fixes the issue.

Interesting. Do you want me to add or change something in this PR now? Or should I wait for you to look into this?

I created new issues for the resize and grey border thing:
https://github.com/Thinkofname/stylish/issues/25
https://github.com/Thinkofname/stylish/issues/24

**Comment by Thinkofname** [comment]
> Interesting. Do you want me to add or change something in this PR now? Or should I wait for you to look into this?
Might as well add a work around for now with a note in this PR. As for the TODO's they look fine so remove those comments as well and i'll merge.

**Comment by anderejd** [comment]
Tested filter order by comparing to firefox:
screen shot 2017-11-18 at 14 20 30

Filter values were chosen to look nice in combination with the demo.rs styling. When rendered in reverse order the logo should look black instead.

**Comment by Thinkofname** [comment]
Thanks!

**Pull request merged**
